---
title: "Cohort Statistics"
output: html_document
date: "2025-10-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

packages
```{r packages}
library(ggplot2)
library(ggpubr)
library(dplyr)
library(rlang)
```

load data
```{r load data}
project_dir<-"~/Projects/R_packages/scDNA_NPM1/"

data_out<-read.csv(paste0(project_dir,"Data/Figure_1_sample_statistics_input.csv"))%>%
                  mutate(Stage=factor(Stage,levels=c("Diagnosis","CR","Relapse")))%>%
                  mutate(Epi_group=factor(Epi_group,levels=c("None","DNMT3A","TET2","IDH","Combo")))%>%
                  mutate(Sig_group=factor(Sig_group,levels=c("None","RAS","FLT3","R+F")))

```

plotting function
```{r plot loop}
library("ggsignif")              
make_boxplot <- function(df, group_var, y_var, palette="Set2",
                         stage_filter=NULL, add_p=TRUE,exclude_CR=FALSE,
                         test="t.test", hide_ns=FALSE) {

  group_sym <- sym(group_var)
  y_sym <- sym(y_var)

  # Filter data by stage if requested
  if (exclude_CR) {
    df <- df %>% filter(Stage != "CR")
  }
  
  # Filter data by stage if requested
  if (!is.null(stage_filter)) {
    df <- df %>% filter(Stage == stage_filter) 
  }

  # Skip if empty (e.g., Stage doesn’t exist)
  if (nrow(df) == 0) return(NULL)

  # Define pairwise comparisons

  # Remove groups with fewer than 2 non-missing observations
  df_valid <- df %>%
    group_by(!!sym(group_var)) %>%
    filter(sum(!is.na(!!sym(y_var))) >= 2) %>%
    ungroup()
  
  # Skip if not enough groups left
  if (length(unique(df_valid[[group_var]])) < 2) {
    return(NULL)
  }
  
  df_valid[[group_var]] <- droplevels(df_valid[[group_var]])

  # Run pairwise Wilcoxon only on valid groups
  statistical_output <- df_valid %>%
    rstatix::pairwise_wilcox_test(
      formula = as.formula(paste(y_var, "~", group_var)),
      p.adjust.method = "fdr"
    )
  
  significant<- statistical_output%>%
                        filter(p.adj.signif!="ns")
  
  comparisons_sig<-c()
  if(nrow(significant)==0){
    comparisons_sig<-c()
  } else {
    comparisons_sig<-significant%>%
                       filter(p.adj.signif!="ns")%>%
                        {purrr::map2(.$group1, .$group2, ~ c(.x, .y))}
  }

  max_y<-df%>%pull(!!y_sym)%>%max
                
  p <- ggplot(df_valid, aes(x = droplevels(!!group_sym), y = !!y_sym, fill = !!group_sym)) +
    geom_boxplot(outlier.shape = NA, alpha = 0.8) +
    geom_jitter(width=0.25,size=0.7,height = 0) +
    scale_fill_manual(values = palette) +
    theme_pubr(base_size = 8) +
    theme(legend.position = "none")+
    theme(axis.text.x=element_text(angle=45,hjust=1,vjust=1),axis.title = element_blank())

  # Add stats
    p <- p + stat_pvalue_manual(data = statistical_output,y.position = max_y*1.075,step.increase =0.1,hide.ns = T,vjust = 0.2,label ="p.adj.signif")+
          coord_cartesian(clip = "off",ylim = c(0,max_y*(1+length(comparisons_sig)*.1)))

  return(list("plot"=p,
              "stats"=statistical_output))
}
```

plot variables
```{r}
metrics <- c("Number_of_clones", "Number_of_mutations",
             "Number_of_mutations_in_dominant_clone",
             "Dominant_clone_size", "Shannon")
groups <- c("Epi_group", "Sig_group")
stages <- c("Diagnosis", "Relapse")
stages_and_CR<-c("Diagnosis","CR", "Relapse")
```


colors
```{r colors}
color_scheme=list("Epi_group"=c("None" = "grey65", "DNMT3A" = "#FDA44B", "TET2" = "#85010C","IDH"="#1A62A4","Combo"="#CCA4FC"),
                  "Sig_group"=c("None" = "grey65", "RAS" = "#EA5B00", "FLT3" = "#298C1F","R+F"="#562887"),
                  "Stage_colors"=c("Diagnosis"="#E4C04C","CR"="#9C3130","Relapse"="#A8C2DA"))
```


generate plots
```{r}
stage_split_plots <- list()
for (st in stages) {
  for (grp in groups) {
    for (met in metrics) {
      name <- paste(st, grp, met, sep = "-")
      stage_split_plots[[name]] <- make_boxplot(
        df = data_out,
        group_var = grp,
        y_var = met,
        stage_filter = st,
        palette = color_scheme[[grp]],
      )
    }
  }
}
```

```{r}
all_stages_plots<-list()
for (grp in groups) {
    for (met in metrics) {
      name <- paste("All_stages",grp, met, sep = "-")
      all_stages_plots[[name]] <- make_boxplot(
        df = data_out,
        group_var = grp,
        exclude_CR=TRUE,
        y_var = met,
        palette = color_scheme[[grp]],
        stage_filter = NULL
      )
    }
  }
```


```{r}
By_Stage_plots<-list()
for (met in metrics) {
      name <- paste("By_Stage", met, sep = "-")
      By_Stage_plots[[name]] <- make_boxplot(
        df = data_out,
        group_var = "Stage",
        y_var = met,
        palette = color_scheme[["Stage_colors"]],
        stage_filter = NULL
      )
  }
```

save plots
```{r save plots}
combined_plots<-c(all_stages_plots,stage_split_plots,By_Stage_plots)
for (nm in names(combined_plots)) {
  if (!is.null(combined_plots[[nm]])) {
    ggsave(filename = paste0(project_dir,"/Results/",nm, ".pdf"),
           plot = combined_plots[[nm]]$plot,
           width = 1.75, height = 3)
  }
}
```


statistics
```{r statix}
combined_plots<-c(all_stages_plots,stage_split_plots,By_Stage_plots)
for (nm in names(combined_plots)) {
  if (!is.null(combined_plots[[nm]])) {
    write.csv(file = paste0(project_dir,"/Results/",nm, "_stats.csv"),
             x = combined_plots[[nm]]$stats,row.names = F)
  }
}
```

