---
title: 'scDNA: NPM1 Figure S2C'
output: html_document
date: "2026-02-22"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(Seurat)
library(dplyr)
library(RColorBrewer)
library(tidyr)
library(ggplot2)
library(tibble)
```

```{r load data,cache=T}
project_dir<-"~/Projects/R_packages/scDNA_NPM1/"
final_s_subset_1k_live<-readRDS(file=paste0(project_dir,"Data/global_seurat.rds"))
```

```{r consolidate genotypes}
new_genotype_info<-final_s_subset_1k_live@meta.data%>%
              select(Patient,Stage_code,harmony_clusters,Genotype,
                    IDH2,IDH1,TET2,DNMT3A,NPM1,NRAS,KRAS,PTPN11,FLT3)%>%
              mutate(new_genotype=case_when(
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==0&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"WT",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"NPM1_only",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0)&FLT3==1~"NPM1_FLT3",
                
                (IDH1==1|IDH1==1)&DNMT3A==0&TET2==0&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"IDH_only",
                (IDH1==0&IDH2==0)&DNMT3A==1&TET2==0&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"DNMT3A_only",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==1&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"TET2_only",
                
                (IDH1==1|IDH2==1)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"IDH_NPM1",
                (IDH1==0&IDH2==0)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"DNMT3A_NPM1",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==1&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"TET2_NPM1",
                
                (IDH1==1|IDH2==1)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==1|KRAS==1|PTPN11==1)&FLT3==0~"IDH_NPM1_MAPK",
                (IDH1==0&IDH2==0)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==1|KRAS==1|PTPN11==1)&FLT3==0~"DNMT3A_NPM1_MAPK",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==1&NPM1==1&(NRAS==1|KRAS==1|PTPN11==1)&FLT3==0~"TET2_NPM1_MAPK",
                
                (IDH1==1|IDH2==1)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0)&FLT3==1~"IDH_NPM1_FLT3",
                (IDH1==0&IDH2==0)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0)&FLT3==1~"DNMT3A_NPM1_FLT3",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==1&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0)&FLT3==1~"TET2_NPM1_FLT3",
                
                (IDH1==1|IDH2==1)&DNMT3A==1&TET2==0&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"DNMT3A_IDH",
                (IDH1==1|IDH2==1)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"DNMT3A_IDH_NPM1",
                (IDH1==1|IDH2==1)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==1|KRAS==1|PTPN11==1)&FLT3==0~"DNMT3A_IDH_NPM1_MAPK",

                TRUE~"Other"
              ))

final_s_subset_1k_live<-AddMetaData(object = final_s_subset_1k_live,
                                    metadata = new_genotype_info$new_genotype,col.name = "new_genotype")

```

```{r color schemes}
TI_colors<- c("grey80",
              brewer.pal(n=9,name="Reds")[c(3,5,7)], #TET2
              brewer.pal(n=9,name="Blues")[c(3,5,7)])  #IDH2

names(TI_colors)<- c("WT", 
                    "TET2-only","TET2-NPM1","TET2-NPM1-MAPK",
                     "IDH-only","IDH-NPM1","IDH-NPM1-MAPK")
                                               
```

```{r define clones and proteins of interest}
clones_of_interest<- list(
  "T_I"=c("TET2_only","IDH_only"),
  "TN_IN"=c("TET2_NPM1","IDH_NPM1"),
  "TNR_INR"=c("TET2_NPM1_MAPK","IDH_NPM1_MAPK"),
  "IN_I"=c("IDH_NPM1","IDH_only"),
  "TN_T"=c("TET2_NPM1","TET2_only"),
  "INR_IN"=c("IDH_NPM1_MAPK","IDH_NPM1"),
  "TNR_TN"=c("TET2_NPM1_MAPK","TET2_NPM1"),
  "TNR_WT"=c("TET2_NPM1_MAPK","WT"))

pairs_of_interest_adjusted<-lapply(clones_of_interest,function(pairs){
  gsub("_","-",pairs)
  })

proteins_of_interest<-c("CD3","CD117","CD34","CD16","CD14","CD11b")
```


```{r calculate differential expression by patient}
data_out<-lapply(clones_of_interest,function(clones){
  subset_s<-subset(final_s_subset_1k_live,new_genotype%in%clones)
  patient_results<-lapply(unique(subset_s$Patient),function(patient){
      
      subset_patient<-subset(subset_s,Patient%in%patient)
      
      Idents(subset_patient)<-"new_genotype"
      if(length(unique(subset_patient$new_genotype))!=2){
        return(NULL)
      } else {
        return(Seurat::FindMarkers(subset_patient,#test.use="wilcox",
                                   features=proteins_of_interest,
                                   ident.1=clones[1],
                                   ident.2=clones[2], 
                                   logfc.threshold = 0
                )%>%
                data.frame()%>%
                tibble::rownames_to_column(var = "Protein")%>%
                mutate(Patient=patient))
      }
  })
  names(patient_results)<-unique(subset_s$Patient)
  return(do.call(rbind,patient_results))
})
names(data_out)<-names(clones_of_interest)
```

```{r log significance}
score_cutoff<--log10(0.01)

tallied_out<-Reduce(bind_rows,lapply(names(data_out),function(sample){
  comparison<-data_out[[sample]]
  if(is.null(comparison)){
    return(NULL)
  } else {
  comparison%>%
        mutate(score=-log10(p_val)*sign(avg_log2FC))%>%
        mutate(group=case_when(
          score>score_cutoff~"Up",
          score<(-score_cutoff)~"Down",
          TRUE~"ns"
        ))%>%
        group_by(Protein)%>%
        count(group)%>%
        mutate(comparison=sample)
  }
}))
```

```{r plot the data}
plot<-ggplot(tallied_out%>%
         mutate(Protein=factor(Protein,levels=(c("CD34", "CD117", "CD11b", "CD14", "CD16", "CD3"))))%>%
         filter(comparison%in%c("TNR_TN","TN_T","TNR_WT")),
       aes(x=Protein,y=n,fill=group))+
       geom_col()+facet_wrap(~comparison,ncol=3)+
       scale_y_continuous(expand = c(0,0))+
       scale_fill_manual(values=c("ns"="grey70",
                                  "Down"=brewer.pal(n=5,name="Blues")[5],
                                  "Up"=brewer.pal(n=5,name="Reds")[5]))+
       theme_classic(base_size = 8)+
       theme(strip.background = element_blank(),axis.text.x = element_text(angle=45,hjust=1))


ggsave(plot, file=paste0(project_dir,"Results/FigureS2B_barplot_final.pdf"),
       width = 4,
       height=2.7)
```


```{r extract significance}
tallied_out%>%
         mutate(Protein=factor(Protein,levels=rev(c("CD34", "CD117", "CD11b", "CD14", "CD16", "CD3"))))%>%
         filter(comparison%in%c("TNR_TN","TN_T","TNR_WT"))%>%
    write.csv(paste0(project_dir,"Results/FigureS2B_counts.csv"),row.names = F,quote = F)
```