---
title: 'scDNA: NPM1 Figure 2A'
output: html_document
date: "2026-02-22"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(Seurat)
library(dplyr)
library(RColorBrewer)
library(tidyr)
library(ggplot2)
library(tibble)
```

```{r load data,cache=T}
project_dir<-"~/Projects/R_packages/scDNA_NPM1/"
final_s_subset_1k_live<-readRDS(file=paste0(project_dir,"Data/global_seurat.rds"))
```

```{r consolidate genotypes}
new_genotype_info<-final_s_subset_1k_live@meta.data%>%
              select(Patient,Stage_code,harmony_clusters,Genotype,
                    IDH2,IDH1,TET2,DNMT3A,NPM1,NRAS,KRAS,PTPN11,FLT3)%>%
              mutate(new_genotype=case_when(
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==0&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"WT",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"NPM1_only",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0)&FLT3==1~"NPM1_FLT3",
                
                (IDH1==1|IDH1==1)&DNMT3A==0&TET2==0&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"IDH_only",
                (IDH1==0&IDH2==0)&DNMT3A==1&TET2==0&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"DNMT3A_only",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==1&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"TET2_only",
                
                (IDH1==1|IDH2==1)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"IDH_NPM1",
                (IDH1==0&IDH2==0)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"DNMT3A_NPM1",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==1&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"TET2_NPM1",
                
                (IDH1==1|IDH2==1)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==1|KRAS==1|PTPN11==1)&FLT3==0~"IDH_NPM1_MAPK",
                (IDH1==0&IDH2==0)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==1|KRAS==1|PTPN11==1)&FLT3==0~"DNMT3A_NPM1_MAPK",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==1&NPM1==1&(NRAS==1|KRAS==1|PTPN11==1)&FLT3==0~"TET2_NPM1_MAPK",
                
                (IDH1==1|IDH2==1)&DNMT3A==0&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0)&FLT3==1~"IDH_NPM1_FLT3",
                (IDH1==0&IDH2==0)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0)&FLT3==1~"DNMT3A_NPM1_FLT3",
                (IDH1==0&IDH2==0)&DNMT3A==0&TET2==1&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0)&FLT3==1~"TET2_NPM1_FLT3",
                
                (IDH1==1|IDH2==1)&DNMT3A==1&TET2==0&NPM1==0&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"DNMT3A_IDH",
                (IDH1==1|IDH2==1)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==0&KRAS==0&PTPN11==0&FLT3==0)~"DNMT3A_IDH_NPM1",
                (IDH1==1|IDH2==1)&DNMT3A==1&TET2==0&NPM1==1&(NRAS==1|KRAS==1|PTPN11==1)&FLT3==0~"DNMT3A_IDH_NPM1_MAPK",

                TRUE~"Other"
              ))

final_s_subset_1k_live<-AddMetaData(object = final_s_subset_1k_live,
                                    metadata = new_genotype_info$new_genotype,col.name = "new_genotype")

```

```{r color schemes}
TI_colors<- c("grey80",
              brewer.pal(n=9,name="Reds")[c(3,5,7)], #TET2
              brewer.pal(n=9,name="Blues")[c(3,5,7)])  #IDH2

names(TI_colors)<- c("WT", 
                    "TET2-only","TET2-NPM1","TET2-NPM1-MAPK",
                     "IDH-only","IDH-NPM1","IDH-NPM1-MAPK"
                         )
                                               
```

```{r pseudobulk,cache=T}
pseudo_seurat <- AggregateExpression(final_s_subset_1k_live, 
                                      assays = "Protein", 
                                      return.seurat = T, 
                                      group.by = c("Patient","Stage_code","new_genotype"))
```

```{r define clones of interest}
clones_of_interest<- list(
  "T_I"=c("TET2_only","IDH_only"),
  "TN_IN"=c("TET2_NPM1","IDH_NPM1"),
  "TNR_INR"=c("TET2_NPM1_MAPK","IDH_NPM1_MAPK"),
  "IN_I"=c("IDH_NPM1","IDH_only"),
  "TN_T"=c("TET2_NPM1","TET2_only"),
  "INR_IN"=c("IDH_NPM1_MAPK","IDH_NPM1"),
  "TNR_TN"=c("TET2_NPM1_MAPK","TET2_NPM1"),
  "TNR_WT"=c("TET2_NPM1_MAPK","WT"))

pairs_of_interest_adjusted<-lapply(clones_of_interest,function(pairs){
  gsub("_","-",pairs)
  })
```



```{r extract pseudobulk data}
pseudo_out<-FetchData(object = pseudo_seurat,vars = c(rownames(pseudo_seurat),
                                                      "Patient",
                                                      "Stage_code",
                                                      "new_genotype"))%>%
            tidyr::pivot_longer(cols = !c(Patient,Stage_code,new_genotype),
                                names_to = "Protein",
                                values_to = "Expression")%>%
            filter(Protein%in%c("CD3","CD117","CD34","CD16","CD14","CD11b"))%>%
            mutate(Protein=factor(Protein,levels=c("CD34", "CD117", "CD11b", "CD14", "CD16", "CD3")))%>%
            filter(new_genotype%in%c("TET2-only","IDH-only",
                                     "TET2-NPM1","IDH-NPM1",
                                     "TET2-NPM1-MAPK","IDH-NPM1-MAPK",
                                     "WT"))%>%
            mutate(Clone=factor(new_genotype,
                                levels=c("WT", 
                                         "TET2-only","TET2-NPM1","TET2-NPM1-MAPK",
                                         "IDH-only", "IDH-NPM1", "IDH-NPM1-MAPK")))
```

```{r plot the data}

plot<-ggplot(pseudo_out,aes(x=Clone,y=Expression,fill=Clone))+
          geom_boxplot(outliers = F)+
          geom_jitter(width = 0.05,size=0.4)+
          facet_grid(~Protein)+
          scale_fill_manual(values=TI_colors)+
          theme_classic(base_size = 8)+
          theme(axis.text.x=element_blank(),
                axis.ticks.x = element_blank(),
                strip.background = element_blank())

ggsave(plot, file=paste0(project_dir,"Results/Figure2A_boxplot_final.pdf"),
       width = 7.5,
       height=2.25)
```

```{r extract significance}
Idents(pseudo_seurat)<-"new_genotype"

pseudo_data_out<-lapply(pairs_of_interest_adjusted[c(1:7)],function(clones){
        return(Seurat::FindMarkers(pseudo_seurat,test.use="DESeq2",
                                   min.cells.group=0,
                                   ident.1=clones[1],
                                   ident.2=clones[2], 
                                   logfc.threshold = 0,
                ) %>%
                data.frame()%>%
                tibble::rownames_to_column(var = "Protein")%>%
                dplyr::select(-pct.1,-pct.2)%>%
                mutate(Comparison=paste(clones[1],"vs",clones[2])))
})
names(pseudo_data_out)<-names(pairs_of_interest_adjusted)[1:7]

do.call(rbind,pseudo_data_out)%>%
    write.csv(paste0(project_dir,"Results/02_21_26/Figure2A_statistics.csv"),row.names = F,quote = F)
```